CREATE TABLE IF NOT EXISTS  HOUSE_ADDRESS (
    ID INT NOT NULL,
    TOWN VARCHAR(255),
    STREET VARCHAR(255),
    `NUMBER` VARCHAR(255),
    PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS HOUSE (
    ID INT NOT NULL,
    ADDRESS_ID INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (ADDRESS_ID) REFERENCES HOUSE_ADDRESS (ID)
);