CREATE TABLE IF NOT EXISTS  HOUSE_ADDRESS (
    ID INT,
    TOWN VARCHAR(255),
    STREET VARCHAR(255),
    `NUMBER` VARCHAR(255)
);

DELETE FROM HOUSE_ADDRESS;

INSERT INTO HOUSE_ADDRESS values (0, 'London', 'Baker St.', '221B');