CREATE TABLE IF NOT EXISTS  HOUSE_ADDRESS (
    ID INT NOT NULL,
    TOWN VARCHAR(255),
    STREET VARCHAR(255),
    `NUMBER` VARCHAR(255),
    PRIMARY KEY (ID)



);

DELETE FROM HOUSE_ADDRESS;

INSERT INTO HOUSE_ADDRESS values (0, 'London', 'Baker St.', '221B');

CREATE TABLE IF NOT EXISTS HOUSE (
    ID INT NOT NULL,
    ADDRESS_ID INT,
    FOREIGN KEY (ADDRESS_ID) REFERENCES HOUSE_ADDRESS (ID)
);